config/routes.rb
Rails.application.routes.draw do

  # root "combos#landing"
  root "combos#index"

  resources :sessions, only: [:new, :create, :destroy]

  resources :combos do
    put :favorite, on: :member
  end

  resources :users do
    resources :combos, shallow: true do
      resources :comments
    end
    resources :comments
  end




  get "favorites/" => "favorites#index"

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :combo
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    if params[:user_id]
      @favorites = Favorite.where(:user_id => params[:user_id])
    else
      @favorites = Favorite.all
    end
  end

end

app/views/favorites/index.html.erb
<h2>My Favorites</h2>

<div class="container">
  <div class="panel-heading sorted_fav">
    <button type="button" class="btn black-background btn-lg">
      <%= link_to "Post a New Combo", new_combo_path%>
    </button>
  </div>
  <div class="panel-body main">
    <ul>
    <% @favorites.order("created_at desc").each do |favorite| %>
    <%= div_for favorite, :class => "col-md-6" do %>
    <p class="title"><%= favorite.combo.character %></p>
    <%= character_img_fav(favorite) %>
    <p>Damage: <%= favorite.combo.damage %></p>
    <p>Difficulty: <%= favorite.combo.difficulty %></p>
    <p>Command</p>
    <p><%= favorite.combo.command %></p>
    <button type="button" class="btn black-background btn-sm">
      <p><%= link_to "Click to View Combo", combo_path(favorite.combo) %></p>
    </button>
    <hr>
    <div class="posted">
      Posted by <%= favorite.combo.user.name %><br>
      on <%= favorite.combo.created_at.localtime.strftime("%m/%d/%Y" " at %I:%M%p") %>
    </div>
    <hr>
    <% end %>
    <% end %>
  </ul>
  </div>
</div>