config/routes.rb
Rails.application.routes.draw do

  # root "combos#landing"
  root "combos#index"

  resources :sessions, only: [:new, :create, :destroy]

  resources :combos do
    put :favorite, on: :member
  end

  resources :users do
    resources :combos, shallow: true do
      resources :comments
    end
    resources :comments
  end




  get "favorites/" => "favorites#index"

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/models/combo.rb
class Combo < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "500x500>", small: "250x250>", thumb: "100x100>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user, :foreign_key => "user_id"

  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :user


end

app/controllers/combos_controller.rb
class CombosController < ApplicationController

  layout false, only: [:landing]

  before_action :set_combo, only: [:show, :edit, :update, :destroy, :favorite]

  before_action :authorize, except: [:index, :show, :landing]

  def favorite
    type = params[:type]
    if type == "favorite"
      current_user.favorite_combos << @combo unless current_user.favorite_combos.exists?(@combo)
      redirect_to combo_path
      flash[:notice] = "Added to Favorites"
    elsif type =="unfavorite"
      current_user.favorite_combos.delete(@combo)
      redirect_to combo_path
      flash[:warning] = "Removed from Favorites"
    else
      redirect_to :back, notice: 'Nothing happened.'
    end
  end

  def index
    if params[:character]
      @combos = Combo.where(:character => params[:character])
    elsif params[:user_id]
      @combos = Combo.where(:user_id => params[:user_id])
    elsif params[:sort]
      @combos = Combo.order(params[:sort])
    else
    @combos = Combo.all
    end
  end

  def show
    @comment = Comment.new
  end

  def new
    @combo = Combo.new
    @comment = Comment.new(combo_id: params[:combo_id])
  end

  def create
    @combo = current_user.combos.create(combo_params)
    if @combo.save
      flash[:success] = "Combo succesfully created"
      redirect_to combos_path
    else
      render :new
    end
  end

  def edit
    redirect_to combos_path, alert: 'Only the original User can perform this action' if current_user != @combo.user
  end

  def update
    if @combo.update_attributes(combo_params)
      redirect_to @combo
    else
      render :edit
    end
  end

  def destroy
    @combo.destroy
    redirect_to combos_path
  end


  private
  def combo_params
    params.require(:combo).permit(:character, :difficulty, :damage, :command, :image)
  end

  def set_combo
    @combo = Combo.find(params[:id])
  end
end

app/views/combos/edit.html.erb
<h2>Edit Your Combo</h2>

<div class="container show">
  <div class="col-lg-10">
    <div class="panel-body main">
      <ul>
      <div class="info comment_form">
          <%= form_for @combo, url: combo_path, html: { multipart: true } do |form| %>
          <%= form.label :character %>
          <%= form.select :character, options_for_select(list) %> <br>

          <%= form.label :difficulty %>
          <%= form.select :difficulty , ['Beginner', 'Intermediate', 'Advanced'] %><br>

          <%= form.label :damage %>
          <%= form.text_field :damage %><br><br>

          <%= form.label :command %>
          <%= form.text_area :command %><br><br>

          <%= form.file_field :image %><br><br>

          <%= form.submit 'Edit this combo' %>
          <% end %>
      </div>
      </ul>
    </div>
  </div>
  <button type="button" class="btn black-background btn-md">
    <%= link_to "Cancel edit and go back", @combo %>
  </button>
</div>

app/views/combos/index.html.erb
<div class="container">
  <div class="panel-heading sorted">
    <div class="new_button">
      <button type="button" class="btn black-background btn-lg">
        <%= link_to "Post a New Combo", new_combo_path%>
      </button>
    </div>
    <div class="dropdown">
    <button class="btn dropdown-toggle filter" type="button" id="dropdownMenuButton" data-toggle="dropdown">
      SORT
    </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <li><%= link_to "DAMAGE ⇧", :sort => 'Damage' %></li>
        <li><%= link_to "DAMAGE ⇩", :sort => 'Damage DESC' %></li>
      </div>
    </div>
  </div>

  <div class="panel-body main">
    <% @combos.order("created_at desc").each do |combo| %>
    <div class="col-md-6 col-sm-6 ">
      <p class="title"><%= combo.character %></p>
      <%= character_img(combo) %>
      <p>Damage: <%= combo.damage %></p>
      <p>Difficulty: <%= combo.difficulty %></p>
      <p>Command: </p>
      <p><%= combo.command %></p>
      <button type="button" class="btn black-background btn-sm">
        <p><%= link_to "Click to View Combo", combo_path(combo) %></p>
      </button>
      <hr>
      <div class="posted">
        Posted by <%= combo.user.name %><br>
        on <%= combo.created_at.localtime.strftime("%m/%d/%Y" " at %I:%M%p") %>
      </div>
      <hr>
      <div class="col-xs-12">
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/combos/landing.html.erb
<!-- <body>

<div class="landing">
<img src="https://streetfighter.com/wp-content/uploads/2015/10/facebook-featured.jpg" alt="">
</div>

</body>
 -->

app/views/combos/new.html.erb
<h2>Create A New Combo To Share</h2>

<div class="container show">
  <div class="col-lg-10">
    <div class="panel-body main">
      <ul>
      <div class="info comment_form">
          <%= form_for @combo, url: combos_path, html: { multipart: true } do |form| %>
          <%= form.label :character %>
          <%= form.select :character, options_for_select(list) %><br>

          <%= form.label :difficulty %>
          <%= form.select :difficulty , ['Beginner', 'Intermediate', 'Advanced'] %><br>

          <%= form.label :damage %>
          <%= form.text_field :damage %><br><br>

          <%= form.label :command %>
          <%= form.text_area :command %><br><br>

          <%= form.file_field :image %><br><br>

          <%= form.submit 'Create Post!' %>
          <% end %>
      </div>
      </ul>
    </div>
  </div>
    <button type="button" class="btn black-background btn-md">
      <%= link_to "Go back to all Combos", combos_path %>
    </button>
</div>

app/views/combos/show.html.erb
<div class="container show">
  <div class="col-lg-10">
    <div class="panel-body main">
      <ul>
      <div class="info col-md-3">
        <%= character_img(@combo) %>
        <p><%= @combo.character %></p>
        <p>Damage:   <%= @combo.damage %></p>
        <p>Difficulty:   <%= @combo.difficulty %></p>
        <br>
        <p>Command:</p>
        <p><%= @combo.command %></p>
      </div>
      </ul>


      <% if @combo.image.file? %>
        <%= image_tag(@combo.image.url, :class => "style_gif") %>
      <% else %>
        &nbsp;
      <% end %>


      <div class="posted">
        Posted by <%= @combo.user.name %>
        on <%= @combo.created_at.localtime.strftime("%m/%d/%Y" " at %I:%M%p") %>
      </div>

      <% if current_user == @combo.user %>
        <p><%= link_to "Edit this Combo", edit_combo_path(@combo) %></p>
        <br>
        <button type="button" class="btn black-background btn-sm">
          <%= link_to "DELETE THIS COMBO", combo_path, method: :delete, data: { confirm: "Are you sure you want to delete this Combo?"} %>
        </button>
      <% end %>


      <div class="card">
        <div class="card-block">
          <% @combo.comments.order("created_at asc").each do |e| %>
          <div class="card-text">
            <br>
            <%= e.content %>
          </div>
        <div class = "postedby">
          Posted by <%= e.user.name %>
          on <%= e.created_at.localtime.strftime("%m/%d/%Y" " at %I:%M%p") %>
        </div>
        <hr>
        <% if current_user == e.user %>
          <%= link_to "Edit comment", edit_comment_path(e) %>
          &nbsp; |&nbsp;
          <%= link_to 'Delete comment', e, method: :delete, data: {confirm: 'Are you sure????'} %>
          <% end %>
        <% end %>
        </div>
      </div>

      <div class="comment_form">
        <% if current_user %>
        <%= form_for [@combo, @comment] do |f| %>
        <%= f.text_area :content, placeholder: "Type comment here..." %><br>
        <%= f.submit 'submit new comment' %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="buttons">
  <% if current_user %>
    <button type="button" class="btn btn-success">
      <%= link_to "Favorite",   favorite_combo_path(@combo, type: "favorite"), method: :put %>
    </button>
    <button type="button" class="btn btn-danger">
      <%= link_to "Unfavorite", favorite_combo_path(@combo, type: "unfavorite"), method: :put %>
    </button>
  <% end %>
  <br>
  <br>
  <br>
  <button type="button" class="btn black-background btn-md">
    <%= link_to "Go back to all Combos", combos_path %>
  </button>
  </div>
</div>