config/routes.rb
Rails.application.routes.draw do

  # root "combos#landing"
  root "combos#index"

  resources :sessions, only: [:new, :create, :destroy]

  resources :combos do
    put :favorite, on: :member
  end

  resources :users do
    resources :combos, shallow: true do
      resources :comments
    end
    resources :comments
  end




  get "favorites/" => "favorites#index"

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SF V Dojo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
  </head>
  <body class="parallax">




    <nav class="navbar navbar-inverse mobile">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><a href="/combos">Home</a></li>
            <li>
              <% if current_user %>
                <%= link_to "My Combos", combos_path(:user_id => current_user) %>
              <% end %>
            </li>
            <li>
              <% if current_user %>
                <%= link_to "My Favorites", favorites_path(:user_id => current_user)  %>
              <% end %>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Find Combos by Character <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "All", combos_path %></li>
                <li><%= link_to "Alex", combos_path(:character=>"Alex") %></li>
                <li><%= link_to "Balrog", combos_path(:character=>"Balrog") %></li>
                <li><%= link_to "Birdie", combos_path(:character=>"Birdie") %></li>
                <li><%= link_to "Cammy", combos_path(:character=>"Cammy") %></li>
                <li><%= link_to "Chun-Li", combos_path(:character=>"Chun-Li") %></li>
                <li><%= link_to "Dhalsim", combos_path(:character=>"Dhalsim") %></li>
                <li><%= link_to "FANG", combos_path(:character=>"FANG") %></li>
                <li><%= link_to "Guile", combos_path(:character=>"Guile") %></li>
                <li><%= link_to "Ibuki", combos_path(:character=>"Ibuki") %></li>
                <li><%= link_to "Karin", combos_path(:character=>"Karin") %></li>
                <li><%= link_to "Ken", combos_path(:character=>"Ken") %></li>
                <li><%= link_to "Laura", combos_path(:character=>"Laura") %></li>
                <li><%= link_to "M. Bison", combos_path(:character=>"M. Bison") %></li>
                <li><%= link_to "Nash", combos_path(:character=>"Nash") %></li>
                <li><%= link_to "Necalli", combos_path(:character=>"Necalli") %></li>
                <li><%= link_to "Rashid", combos_path(:character=>"Rashid") %></li>
                <li><%= link_to "R. Mika", combos_path(:character=>"R. Mika") %></li>
                <li><%= link_to "Ryu", combos_path(:character=>"Ryu") %></li>
                <li><%= link_to "Vega", combos_path(:character=>"Vega") %></li>
                <li><%= link_to "Zangief", combos_path(:character=>"Zangief") %></li>
              </ul>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if current_user %>
               <%= link_to current_user.name, current_user%>
              <% end %>
            </li>
            <li>
              <% if current_user %>
               <%= link_to 'Log Out', session_path('dummy'), method: :delete %>
               <% else %>
                 <li><%= link_to 'Log In', login_path %></li>
                 <li><%= link_to 'Sign Up', new_user_path %></li>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>





  <% flash.each do |key, value| %>
  <div class="alert alert-success alert-<%= key %>"><%= value %></div>
  <% end %>

  <%= yield %>

  </body>
</html>